name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Install bundler
        run: gem install bundler -v 2.4.22

      - name: Check for Gemfile
        run: ls -la /Users/ramazangasratov/Desktop/FirstDemo/
        continue-on-error: true

      - name: Install dependencies
        run: bundle install
        working-directory: /Users/ramazangasratov/Desktop/FirstDemo/

      - name: Setup Fastlane
        run: bundle exec fastlane ci_build
        working-directory: /Users/ramazangasratov/Desktop/FirstDemo/
